repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
    -   id: check-symlinks
    -   id: check-yaml
    -   id: debug-statements
        exclude: tests/
    -   id: destroyed-symlinks
    -   id: end-of-file-fixer
        exclude: tests/test_changes/
        files: \.(py|sh|rst|yml|yaml)$
    -   id: mixed-line-ending
    -   id: trailing-whitespace
        files: \.(py|sh|rst|yml|yaml)$
  # - repo: https://github.com/PyCQA/flake8
  #   rev: 6.1.0
  #   hooks:
  #   -   id: flake8
  #       additional_dependencies: [
  #           'flake8-blind-except',
  #           'flake8-docstrings',
  #           'flake8-bugbear',
  #           'flake8-comprehensions',
  #           'flake8-docstrings',
  #           'flake8-implicit-str-concat',
  #           'pydocstyle>=5.0.0',
  #       ]
  #       exclude: ^tests/test_cases/no_closing_bracket\.py$
  - repo: https://github.com/psf/black
    rev: 23.10.0
    hooks:
    -   id: black
        exclude: tests/
        args: [--check]
  -   repo: https://github.com/asottile/pyupgrade
      rev: v3.15.0
      hooks:
      -   id: pyupgrade
  # - repo: https://github.com/pycqa/isort
  #   rev: 5.12.0
  #   hooks:
  #     - id: isort
  #       name: isort (python)
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
